# Site settings
title: Recursive Jr
email: contato@recursive.com.br
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: recursivejr
github_username:  recursivejr
absolute_url:https://raw.githubusercontent.com/recursivejr/recursivejr.github.io/master

# Build settings
markdown: kramdown
